export { default as Home } from "./home/index.js"
export { default as Contact } from "./contact/index.js"
export { default as Experience } from "./experience/index.js"
export { default as Project } from "./projects/index.js"
export { default as Blog } from "./blogs/index.js"
